name: Unit tests

on: [push]

jobs:

  build:
    name: "Build & Test"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .net8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --logger trx --collect:"XPlat Code Coverage" --results-directory "TestOutput"

      - name: Format Test Results
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}  # Ensures we still HTML format the results even if previous step fails
        with:
          name: Test Results
          path: TestOutput/*.trx
          reporter: dotnet-trx
          use-actions-summary: 'true'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: unit-test-output
          path: TestOutput
          
  coverage:
      name: Test Coverage
      if: ${{ always() }}
      runs-on: ubuntu-latest
      needs: build
      
      steps:

      - name: Download test output
        uses: actions/download-artifact@v4
        with:
          name: unit-test-output
        
      - name: Format Test Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./**/coverage.cobertura.xml
          badge: true
          format: markdown
          output: both

      - name: Test Coverage to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

